<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>admin</title>
    <?php require_once('vue/template/head.phtml'); ?>

  </head>

  <body>

    <header>
      <h1>AJOUT <?= $vue['titre'] ?></h1>
    </header>

    <main>
      <form id="formulaire_admin" action="" method="post" enctype="multipart/form-data">
        <?= $vue['formulaire'] ?>
        <input type="submit" value="Ajouter"><br><br>
      </form>
    </main>


    <footer>
      <a href="<?= $vue['retour'] ?>"><button type="button" name="button">Annuler</button></a>
    </footer>

  </body>
</html>
