<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>admin</title>
  </head>
  <body>
    <h1>SUPPRESSION</h1>
    <h2>Voulez-vous supprimer la ligne n°<?= $vue['ligne'] ?> de la table "<?= $vue['table'] ?>" ?</h2>
    <form action="" method="post">
      <input type="hidden" name="id" value="<?= $vue['ligne'] ?>">
      <input type="submit" name="suppression" value="OUI">
    </form>
    <a href="<?= $vue['retour'] ?>"><button type="button" name="button">NON</button></a>
    <?= $vue['affichage'] ?>

  </body>
</html>
