
  <meta charset="UTF-8">
  <meta name="viewport" content="initial-scale=1.0, user-scalable=yes" />

  <title>Porte folio VLH Nantes <?= $vue['title'] ?></title>
  <link rel="shortcut icon" type="image/jpg" href="img/icon_onglet.png">

  <link rel="stylesheet" href="vendor/reset.css">
  <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="css/final.css">

  <script type="text/javascript" src="vendor/jquery-2.1.4.js"></script>
  <script type="text/javascript" src="vendor/jquery-ui.js"></script>
