<!-- ********************** VUE INDEX ************************** -->

<!DOCTYPE html>
<html lang="fr">
<head>
  <?php require_once('vue/template/head.phtml') ?>
</head>
<body>
  <div id="papierPeint"></div>

  <header>

  </header>


  <main>
    <section id="mentions_legales">
      <h2>Mentions légales</h2>
      </br>
      <div id="body_mentions">
        Merci de lire avec attention les différentes modalités d’utilisation du
        présent site avant d’y parcourir ses pages. En vous connectant sur ce site,
        vous acceptez sans réserves les présentes modalités. Aussi, conformément à
        l’article n°6 de la Loi n°2004-575 du 21 Juin 2004 pour la confiance dans
        l’économie numérique, les responsables du présent site internet <a
        href="http://www.vlh.space">www.vlh.space</a>
        sont :

        <p ><span ><b>Editeur du Site : </b><br><br></span></p>
        Nom : LE HENAFF   <br>
        Prénom : Vincent <br>
        12 rue des colombes 44470 CARQUEFOU <br>
        Email : contact@vlh.space <br>
        Site Web : <a href="http://www.vlh.space">www.vlh.space</a>
        </br>

        <p ><span ><b>Hébergement :</b></span> <br><br></p>
        Hébergeur : GANDI SAS <br>
        63-65 boulevard Massena à Paris (75013) FRANCE, <br>
        Site Web :  <a href="http://www.gandi.net">www.gandi.net</a>
        </br>

        <p ><span ><b>Développement</b><b> : </b><br><br></span></p>
        LE HENAFF Vincent <br>
        Adresse : 12 rue des colombes 44470 CARQUEFOU <br>
        Site Web : <a href="http://www.vlh.space">www.vlh.space</a>
        </br>

        <p ><span ><b>Conditions d’utilisation : </b><br><br></span></p>
        Ce site (<a href="http://www.vlh.space">www.vlh.space</a>) est proposé en différents langages web (HTML, HTML5, Javascript, CSS, etc…) pour un meilleur confort d'utilisation et un graphisme plus agréable, nous vous recommandons de recourir à des navigateurs modernes comme Internet explorer, Safari, Firefox, Google Chrome, etc…
        Les mentions légales ont été générées sur le site <a title="générateur de mentions légales pour site internet gratuit" href="http://www.generateur-de-mentions-legales.com">Générateur de mentions légales</a>, offert par <a title="imprimerie paris, imprimeur paris" href="http://welye.com">Welye</a>.<br><br>

        <span >LE HENAFF Vincent</span> met en œuvre tous les moyens dont elle dispose, pour assurer une information fiable et une mise à jour fiable de ses sites internet. Toutefois, des erreurs ou omissions peuvent survenir. L'internaute devra donc s'assurer de l'exactitude des informations auprès de Vincent, et signaler toutes modifications du site qu'il jugerait utile. N'est en aucun cas responsable de l'utilisation faite de ces informations, et de tout préjudice direct ou indirect pouvant en découler.<br><br>

        <span><b>Cookies</b></span> : Le site <a href="http://www.vlh.space">www.vlh.space</a> peut-être amené à vous demander l’acceptation des cookies pour des besoins de statistiques et d'affichage. Un cookies est une information déposée sur votre disque dur par le serveur du site que vous visitez. Il contient plusieurs données qui sont stockées sur votre ordinateur dans un simple fichier texte auquel un serveur accède pour lire et enregistrer des informations . Certaines parties de ce site ne peuvent être fonctionnelles sans l’acceptation de cookies.<br><br>

        <span><b>Liens hypertextes</b></span> : Les sites internet de peuvent offrir des liens vers d’autres sites internet ou d’autres ressources disponibles sur Internet. LE HENAFF Vincent ne
        e répond pas de la disponibilité de tels sites et sources externes, ni ne la garantit. Elle ne peut être tenue pour responsable de tout dommage, de quelque nature que ce soit, résultant du contenu de ces sites ou sources externes, et notamment des informations, produits ou services qu’ils proposent, ou de tout usage qui peut être fait de ces éléments. Les risques liés à cette utilisation incombent pleinement à l'internaute, qui doit se conformer à leurs conditions d'utilisation.

        Les utilisateurs, les abonnés et les visiteurs des sites internet de ne peuvent mettre en place un hyperlien en direction de ce site sans l'autorisation expresse et préalable de LE HENAFF Vincent.

        Dans l'hypothèse où un utilisateur ou visiteur souhaiterait mettre en place un hyperlien en direction d’un des sites internet de LE HENAFF Vincent, il lui appartiendra d'adresser un email accessible sur le site afin de formuler sa demande de mise en place d'un hyperlien. LE HENAFF Vincent se réserve le droit d’accepter ou de refuser un hyperlien sans avoir à en justifier sa décision.
        </br>
        <p ><span ><b>Services fournis : </b></span></p><br>
        L'ensemble des activités ainsi que ses informations sont présentés sur notre site <a href="http://www.vlh.space">www.vlh.space</a>.
        LE HENAFF Vincent s’efforce de fournir sur le site www.vlh.space des informations aussi précises que possible. les renseignements figurant sur le site <a href="http://www.vlh.space">www.vlh.space</a> ne sont pas exhaustifs et les photos non contractuelles. Ils sont donnés sous réserve de modifications ayant été apportées depuis leur mise en ligne. Par ailleurs, tous les informations indiquées sur le site <a href="http://www.vlh.space">www.vlh.space</a> sont données à titre indicatif, et sont susceptibles de changer ou d’évoluer sans préavis.
        </br>
        <p ><span ><b>Limitation contractuelles sur les données : </b></span></p><br>
        Les informations contenues sur ce site sont aussi précises que possible et le site remis à jour à différentes périodes de l’année, mais peut toutefois contenir des inexactitudes ou des omissions. Si vous constatez une lacune, erreur ou ce qui parait être un dysfonctionnement, merci de bien vouloir le signaler par email, à l’adresse contact@vlh.space, en décrivant le problème de la manière la plus précise possible (page posant problème, type d’ordinateur et de navigateur utilisé, …).

        Tout contenu téléchargé se fait aux risques et périls de l'utilisateur et sous sa seule responsabilité. En conséquence, ne saurait être tenu responsable d'un quelconque dommage subi par l'ordinateur de l'utilisateur ou d'une quelconque perte de données consécutives au téléchargement. De plus, l’utilisateur du site s’engage à accéder au site en utilisant un matériel récent, ne contenant pas de virus et avec un navigateur de dernière génération mis-à-jour.

        Les liens hypertextes mis en place dans le cadre du présent site internet en direction d'autres ressources présentes sur le réseau Internet ne sauraient engager la responsabilité de LE HENAFF Vincent.
        </br>
        <p ><span ><b>Propriété intellectuelle :</b><br><br></span></p>
        Tout le contenu du présent sur le site <a href="http://www.vlh.space">www.vlh.space</a>, incluant, de façon non limitative, les graphismes, images, textes, vidéos, animations, sons, logos, gifs et icônes ainsi que leur mise en forme sont la propriété exclusive de LE HENAFF Vincent à l'exception des marques, logos ou contenus appartenant à d'autres sociétés partenaires ou auteurs.

        Toute reproduction, distribution, modification, adaptation, retransmission ou publication, même partielle, de ces différents éléments est strictement interdite sans l'accord exprès par écrit de LE HENAFF Vincent. Cette représentation ou reproduction, par quelque procédé que ce soit, constitue une contrefaçon sanctionnée par les articles L.335-2 et suivants du Code de la propriété intellectuelle. Le non-respect de cette interdiction constitue une contrefaçon pouvant engager la responsabilité civile et pénale du contrefacteur. En outre, les propriétaires des Contenus copiés pourraient intenter une action en justice à votre encontre.
        </br>
        <p ><span ><b>Déclaration à la CNIL : </b><br><br></span></p>
        Conformément à la loi 78-17 du 6 janvier 1978 (modifiée par la loi 2004-801 du 6 août 2004 relative à la protection des personnes physiques à l'égard des traitements de données à caractère personnel) relative à l'informatique, aux fichiers et aux libertés, ce site n'a pas fait l'objet d'une déclaration  auprès de la Commission nationale de l'informatique et des libertés (<a href="http://www.cnil.fr/">www.cnil.fr</a>).
        </br>
        <p ><span ><b>Litiges : </b><br><br></span></p>
        Les présentes conditions du site <a href="http://www.vlh.space">www.vlh.space</a> sont régies par les lois françaises et toute contestation ou litiges qui pourraient naître de l'interprétation ou de l'exécution de celles-ci seront de la compétence exclusive des tribunaux. La langue de référence, pour le règlement de contentieux éventuels, est le français.
        </br>
        <p ><span ><b>Crédits :</b><br><br></span></p>
        Icons made by <a href="http://www.freepik.com" title="Freepik">Freepik</a> from <a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a><br>
        Icons made by <a href="http://www.flaticon.com/authors/yannick" title="Yannick">Yannick</a> from <a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a><br>
        Icons made by <a href="http://www.flaticon.com/authors/madebyoliver" title="Madebyoliver">Madebyoliver</a> from <a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a><br>

      </div>


    </section>


</main>

<footer>
  <a href="index.php" >Retour vers le site</a><br><br>

  <p>2016 &copy; Vincent LE HENAFF  </p><br><br>

</footer>

</body>
</html>
